name: tempurehere
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.14
  http: ^1.2.2
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/chuva.png
    - assets/image/chuva_trovao.png
    - assets/image/neve.png
    - assets/image/nublado.png
    - assets/image/sol.png
    - assets/image/sol_chuva.png
    - assets/image/sol_nuvem.png